In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf


df = pd.read_csv("reviews_final_modelled.csv")

df.head()

,id,reviews.val.date,reviews.val.helpfulCount,reviews.val.id,careerOpportunities_rating,compBenefits_rating,cultureValues_rating,overall_rating,seniorManagement_rating,worklifeBalance_rating,...,reviews.val.summaryPoints.outlook,reviews.val.summaryPoints.recommend,overview.industry,overview.sector,header.employerName,gaTrackerData.empName,overall_review,language,rating_class,cleaned_review
0,3087,2008-06-11,0,5865,4.0,3.0,0,4,3.5,3.0,...,0,1,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Compugen USA,Compugen (isreal),"Good place to work, not for exit. Great workin...",en,Positive,good place not exit great envirement not focus...
1,147399,2008-06-12,1,12735,5.0,4.0,0,5,4.0,3.5,...,0,1,Research & Development,Business Services,ManTech,ManTech,A top notch place to work for people in the hi...,en,Positive,top notch place people hi tech defense service...
2,82943,2008-06-12,5,13384,4.0,3.0,0,4,3.5,1.5,...,0,0,Food & Drink Manufacturing,Manufacturing,The Coca-Cola Company,The Coca-Cola Company,Great place to work (if you really love to wor...,en,Positive,great place really love long long hours great ...
3,147399,2008-06-12,2,14896,2.0,2.5,0,2,2.0,3.5,...,0,2,Research & Development,Business Services,ManTech,ManTech,"Mantech, willing to do anything for a buck.. T...",en,Negative,mantech willing anything buck large not set di...
4,54007,2008-06-14,0,20148,3.5,3.0,0,3,3.0,4.0,...,0,0,Electrical & Electronic Manufacturing,Manufacturing,Marvell Technology,Marvell Semiconductor,just a job. not mutural in management level. l...,en,Neutral,job not mutural management level leader market...

In [2]:
print(df['overall_review'].count(),'\n\n',df['overall_rating'].value_counts(),'\n\n',
      df['overall_review'].count()==df['overall_rating'].count())

69339

 5    28731
4    18992
3    10241
1     6183
2     5192
Name: overall_rating, dtype: int64

 True

In [4]:
rating = []
for i in df['overall_rating']:
        if i > 3 : rating.append(1)
        elif i > 2:  rating.append(0)
        else:       rating.append(-1)

df['overall_rating2'] = rating
    
df.head()

,id,reviews.val.date,reviews.val.helpfulCount,reviews.val.id,careerOpportunities_rating,compBenefits_rating,cultureValues_rating,overall_rating,seniorManagement_rating,worklifeBalance_rating,...,reviews.val.summaryPoints.recommend,overview.industry,overview.sector,header.employerName,gaTrackerData.empName,overall_review,language,rating_class,cleaned_review,overall_rating2
0,3087,2008-06-11,0,5865,4.0,3.0,0,4,3.5,3.0,...,1,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Compugen USA,Compugen (isreal),"Good place to work, not for exit. Great workin...",en,Positive,good place not exit great envirement not focus...,1
1,147399,2008-06-12,1,12735,5.0,4.0,0,5,4.0,3.5,...,1,Research & Development,Business Services,ManTech,ManTech,A top notch place to work for people in the hi...,en,Positive,top notch place people hi tech defense service...,1
2,82943,2008-06-12,5,13384,4.0,3.0,0,4,3.5,1.5,...,0,Food & Drink Manufacturing,Manufacturing,The Coca-Cola Company,The Coca-Cola Company,Great place to work (if you really love to wor...,en,Positive,great place really love long long hours great ...,1
3,147399,2008-06-12,2,14896,2.0,2.5,0,2,2.0,3.5,...,2,Research & Development,Business Services,ManTech,ManTech,"Mantech, willing to do anything for a buck.. T...",en,Negative,mantech willing anything buck large not set di...,-1
4,54007,2008-06-14,0,20148,3.5,3.0,0,3,3.0,4.0,...,0,Electrical & Electronic Manufacturing,Manufacturing,Marvell Technology,Marvell Semiconductor,just a job. not mutural in management level. l...,en,Neutral,job not mutural management level leader market...,0

In [5]:
print(df['overall_review'].count(),'\n\n',df['overall_rating2'].value_counts(),'\n\n',
      df['overall_review'].count()==df['overall_rating2'].count())

69339

  1    47723
-1    11375
 0    10241
Name: overall_rating2, dtype: int64

 True

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split,StratifiedKFold
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn import metrics
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import matthews_corrcoef

In [7]:
train_data = df
train_data.shape

(69339, 24)

In [8]:
vectorizer = CountVectorizer(analyzer="word", 
                             preprocessor=None, 
                             stop_words=None, 
                             ngram_range=(1,1),
                            max_features=5000)

In [9]:
train_data_features = vectorizer.fit_transform(df.cleaned_review)
train_data_features = train_data_features.toarray()

In [10]:
X = train_data_features
y = train_data.overall_rating2

In [11]:
print (X.shape) 
print (y.shape)

(69339, 5000)
(69339,)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,random_state=123)

In [13]:
naive = MultinomialNB()
classifier = naive.fit(X_train,y_train)
predict = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(predict,y_test)

print(cm)
print()
print(classification_report(predict,y_test))
print("MCC-Score:", matthews_corrcoef(y_test,predict))

[[1816  333  335]
 [ 725 1234 1741]
 [ 290  986 9875]]

              precision    recall  f1-score   support

          -1       0.64      0.73      0.68      2484
           0       0.48      0.33      0.39      3700
           1       0.83      0.89      0.85     11151

   micro avg       0.75      0.75      0.75     17335
   macro avg       0.65      0.65      0.64     17335
weighted avg       0.73      0.75      0.73     17335

MCC-Score: 0.49681148794747104

In [14]:
accuracy = cm.trace()/cm.sum()
print(accuracy)

0.7456013844822613

In [15]:
x = df.loc[:, df.columns != 'overall_rating2']
test_data_features = vectorizer.fit_transform(x.cleaned_review)
test_data_features = test_data_features.toarray()

In [16]:
y_pred_M = classifier.predict(test_data_features)

In [17]:
print(accuracy_score(y,y_pred_M))

0.7612022094348058

In [19]:
print ("There are %d exampes in our data"  % X.shape[0])
print ("We have made %d wrong predictions - these examples are:" % (y != y_pred_M).sum())  
error = []
for i in range(X.shape[0]):
    if (y[i] != y_pred_M[i]):
        error.append(i)
y_pred = pd.DataFrame(y_pred_M)
y_pred.columns = ["Predict"]

# error_1 = error[16:]
df['Predict'] = y_pred_M
df.iloc[error, 19:25]

There are 69339 exampes in our data
We have made 16558 wrong predictions - these examples are:

,overall_review,language,rating_class,cleaned_review,overall_rating2,Predict
5,Experian is a decent place to work unless you ...,en,Negative,experian decent place unless want grow career ...,-1,0
6,Not a bad place to work. Challenging atmospher...,en,Positive,not bad place challenging atmosphere competent...,1,0
7,Know where you're going?. lack of interdepartm...,en,Neutral,know going lack interdepartmental communicatio...,0,1
9,Too many managers !. Too many managers - many ...,en,Neutral,many managers many managers many layers make s...,0,1
11,The stagnation of a company.. Company has had ...,en,Negative,stagnation no momentum past 4 years bureaucrat...,-1,1
12,Management skills trails MDA's technical growt...,en,Positive,management skills trails mda technical growth ...,1,0
13,MBI an ok place to work. Not a brand name comp...,en,Neutral,mbi ok place not brand name harder apply mba s...,0,-1
15,Nice place to work if you can stand pointy-hai...,en,Neutral,nice place stand pointy haired bosses bureaucr...,0,-1
17,Good in theory..... uneven implementation. The...,en,Negative,good theory uneven implementation organization...,-1,0
21,Heck of a boot camp for all starters with high...,en,Positive,heck boot camp starters high goals achieve lar...,1,0
22,"Maybe, Maybe Not. The best reasons will be tha...",en,Positive,maybe maybe not best reasons ocbc foreign bank...,1,0
24,"The 10,000 foot view. Working with very techni...",en,Positive,10 000 foot view technically competent people ...,1,-1
27,Culture trumps strategy. It is discouraging to...,en,Negative,culture trumps strategy discouraging constantl...,-1,1
28,Mediocrity in a field of many players. Cons\r\...,en,Neutral,mediocrity field many players cons staffing go...,0,-1
29,"Great atmosphere, good pay, but lacking in som...",en,Neutral,great atmosphere good pay lacking imporant are...,0,-1
31,"A pretty good place to work, but could be so m...",en,Positive,pretty good place could much better liberty mu...,1,0
34,Focus more on people development and welfare. ...,en,Negative,focus people development welfare first level m...,-1,0
36,Develpoment/Real Estate/Construction Co with n...,en,Neutral,develpoment real estate construction co no set...,0,1
37,"Decent pay, easy going company. They allow emp...",en,Positive,decent pay easy going allow employees drink jo...,1,-1
42,"working in J&J. lack of transparency, lack of ...",en,Negative,j j lack transparency lack trust good products...,-1,0
43,"Don't rest on one's laurels, go forward, let p...",en,Neutral,rest one laurels go forward let people try bes...,0,-1
44,JLL not ready for FM outsourcing deals. Very l...,en,Negative,jll not ready fm outsourcing deals loz fm expe...,-1,0
50,Kimberly Clark is a great place to work. It's ...,en,Positive,kimberly clark great place great defined organ...,1,0
53,I do not have inspiration for a facny headline...,en,Neutral,not inspiration facny headline usual cons serv...,0,1
62,"CSTS, keep your talents. Management team faile...",en,Negative,csts keep talents management team failed show ...,-1,0
64,Belkin is not the same company it was 10 years...,en,Negative,belkin not 10 years ago wrong direction belkin...,-1,1
69,Good place to move into business. Good career ...,en,Positive,good place move business good career prospects...,1,0
72,"Pleasant, though not inspired. Anti-pragmatic,...",en,Negative,pleasant though not inspired anti pragmatic ov...,-1,0
74,Unfortunately Gallup is eroding their powerful...,en,Negative,unfortunately gallup eroding powerful brand na...,-1,1
75,"Incredibly high staff turnover, for good reaso...",en,Negative,incredibly high staff turnover good reason man...,-1,0
...,...,...,...,...,...,...
69174,There are much better companies to work for. T...,en,Negative,much better companies much centralisation admi...,-1,0
69176,"Good place to advance software career, too muc...",en,Positive,good place advance software career much red ta...,1,0
69185,Software Engineer in Cloud Platform. Since I'm...,en,Neutral,software engineer cloud platform since contrac...,0,1
69192,Junior Analyst. good working environment and c...,en,Positive,junior analyst good environment career opportu...,1,0
69195,Good company. Cool manager no work pressure. G...,en,Positive,good cool manager no pressure growth less,1,0
69197,"Great values. Good values, benefits due to not...",en,Positive,great values good values benefits due not prof...,1,0
69200,Good learning experience. Becomes quickly repe...,en,Neutral,good learning experience becomes quickly repet...,0,1
69206,Software developer. Work life balance\r\nTrans...,en,Positive,software developer life balance transportation...,1,0
69222,Process Associate. A very good company with jo...,en,Positive,process associate good job secuirity low packa...,1,0
69228,Nice Place to Work. Work Life Balance\r\nFlexi...,en,Positive,nice place life balance flexibility change pro...,1,0
69229,Good entry level scientist role. Good training...,en,Positive,good entry level scientist role good training ...,1,0
69237,Digital Marketing - IBM. Good Culture and wor...,en,Positive,digital marketing ibm good culture environment...,1,0
69238,Cognos Senior Administrator. Benefits are very...,en,Neutral,cognos senior administrator benefits limited s...,0,1
69241,Not a culture encouraging creative work. - peo...,en,Negative,not culture encouraging creative people pursui...,-1,0
69253,"Assistant Vice President. Good benefits, bonus...",en,Positive,assistant vice president good benefits bonus h...,1,0
69258,"All over the place. Unstructured, poorly manag...",en,Neutral,place unstructured poorly managed inefficient ...,0,-1
69264,MB Review.. Upper management is not very good ...,en,Neutral,mb review upper management not good mumbai off...,0,1
69268,Poor leadership. Poor management with too man...,en,Negative,poor leadership poor management many leaders t...,-1,0
69271,Not professional. The number two belittling yo...,en,Negative,not professional number two belittling getting...,-1,1
69272,"Good place to work. Less work load, good salar...",en,Positive,good place less load good salary benefits hier...,1,0
69275,Business Analyst at Regulatory Reform. Good pa...,en,Positive,business analyst regulatory reform good pay gr...,1,0
69276,"Working in TD Ameritrade. Good Pay, flex hours...",en,Positive,td ameritrade good pay flex hours highly quali...,1,0
69283,Mixed Feelings. -constant fear of layoffs\r\n-...,en,Neutral,mixed feelings constant fear layoffs managemen...,0,-1
69291,No work life balance. - the environment is not...,en,Negative,no life balance environment not everyone grade...,-1,0
69295,Software Engineer III. Review process is worst...,en,Neutral,software engineer iii review process worst ind...,0,1
69297,Working for the big dog. Nobody does space lik...,en,Positive,big dog nobody space like lockheed martin ethi...,1,-1
69300,Associate Software Engineer. - Best Environmen...,en,Positive,associate software engineer best environment l...,1,0
69313,Better pay for staff. Pay is very low for the ...,en,Neutral,better pay staff pay low skill set required co...,0,1
69314,good work culture. Work culture\r\nproper ince...,en,Positive,good culture culture proper incentives persona...,1,0
69318,"Great ceo, bad middle management. CEO with a v...",en,Positive,great ceo bad middle management ceo vision gro...,1,-1